import * as stylex from "@stylexjs/stylex";

import { tokens } from "../../styles/tokens.stylex.ts";

export const quizDeckStyles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.space[6],
    maxWidth: "42rem",
  },
  header: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: tokens.space[3],
  },
  stats: {
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.space[4],
    fontSize: tokens.fontSize.sm,
    color: tokens.color.inkSecondary,
    fontFamily: tokens.fontFamily.sans,
  },
  progressTrack: {
    width: "100%",
    height: "6px",
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.color.surfaceMuted,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: tokens.color.accent,
    transitionProperty: "width",
    transitionDuration: tokens.duration.normal,
  },
  cardShell: {
    perspective: "1200px",
    minHeight: "18rem",
  },
  cardShellReduced: {
    perspective: "none",
    minHeight: "18rem",
  },
  card: {
    position: "relative",
    width: "100%",
    minHeight: "18rem",
    transformStyle: "preserve-3d",
    transitionProperty: "transform",
    transitionDuration: tokens.duration.slow,
    transitionTimingFunction: "ease",
  },
  cardFlipped: {
    transform: "rotateY(180deg)",
  },
  cardFade: {
    position: "relative",
    width: "100%",
    minHeight: "18rem",
    transitionProperty: "opacity",
    transitionDuration: tokens.duration.normal,
  },
  cardFace: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space[4],
    padding: tokens.space[6],
    borderRadius: tokens.radius.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.color.border,
    backgroundColor: tokens.color.surface,
    backfaceVisibility: "hidden",
  },
  cardBack: {
    transform: "rotateY(180deg)",
  },
  cardFaceStatic: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.space[4],
    padding: tokens.space[6],
    borderRadius: tokens.radius.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.color.border,
    backgroundColor: tokens.color.surface,
  },
  cardFaceHidden: {
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    inset: 0,
  },
  prompt: {
    fontSize: tokens.fontSize.lg,
    fontWeight: 600,
    lineHeight: tokens.lineHeight.tight,
    color: tokens.color.ink,
    fontFamily: tokens.fontFamily.sans,
    margin: 0,
  },
  choices: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.space[2],
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  choiceButton: {
    display: "flex",
    alignItems: "flex-start",
    gap: tokens.space[3],
    width: "100%",
    padding: tokens.space[3],
    borderRadius: tokens.radius.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.color.border,
    backgroundColor: tokens.color.canvas,
    color: tokens.color.ink,
    fontFamily: tokens.fontFamily.sans,
    fontSize: tokens.fontSize.sm,
    textAlign: "left",
    cursor: "pointer",
    transitionProperty: "border-color, background-color",
    transitionDuration: tokens.duration.fast,
  },
  choiceSelected: {
    borderColor: tokens.color.accent,
    backgroundColor: tokens.color.accentSoft,
  },
  choiceCorrect: {
    borderColor: tokens.color.accentInk,
    backgroundColor: tokens.color.accentSoft,
  },
  choiceWrong: {
    borderColor: "#c62828",
    backgroundColor: "#ffebee",
  },
  shortInput: {
    width: "100%",
    padding: tokens.space[3],
    borderRadius: tokens.radius.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.color.border,
    fontFamily: tokens.fontFamily.sans,
    fontSize: tokens.fontSize.md,
    color: tokens.color.ink,
    backgroundColor: tokens.color.canvas,
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.space[3],
    marginTop: "auto",
  },
  primaryButton: {
    paddingBlock: tokens.space[2],
    paddingInline: tokens.space[4],
    borderRadius: tokens.radius.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.color.accentInk,
    backgroundColor: tokens.color.accentInk,
    color: tokens.color.canvas,
    fontFamily: tokens.fontFamily.sans,
    fontSize: tokens.fontSize.sm,
    fontWeight: 500,
    cursor: "pointer",
  },
  secondaryButton: {
    paddingBlock: tokens.space[2],
    paddingInline: tokens.space[4],
    borderRadius: tokens.radius.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens.color.border,
    backgroundColor: "transparent",
    color: tokens.color.ink,
    fontFamily: tokens.fontFamily.sans,
    fontSize: tokens.fontSize.sm,
    cursor: "pointer",
  },
  feedback: {
    fontSize: tokens.fontSize.sm,
    fontFamily: tokens.fontFamily.sans,
    color: tokens.color.inkSecondary,
    margin: 0,
  },
  explanation: {
    fontSize: tokens.fontSize.sm,
    lineHeight: tokens.lineHeight.body,
    color: tokens.color.ink,
    fontFamily: tokens.fontFamily.sans,
    margin: 0,
  },
  sourceLink: {
    fontSize: tokens.fontSize.sm,
    color: tokens.color.accentInk,
    fontFamily: tokens.fontFamily.sans,
  },
  hint: {
    fontSize: tokens.fontSize.sm,
    color: tokens.color.inkTertiary,
    fontFamily: tokens.fontFamily.mono,
  },
});
